dependencies:
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: go-quickstart-jenkinsx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
